"""add user fields

Revision ID: f31d1af5e81d
Revises: 34822ff7b9c4
Create Date: 2024-12-17 21:58:15.078096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f31d1af5e81d'
down_revision: Union[str, None] = '34822ff7b9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(length=32), nullable=False))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('users', 'birth')
    # ### end Alembic commands ###
