"""add answer table and relationships

Revision ID: 33d67323c0b8
Revises: 6afc59f0897e
Create Date: 2024-12-22 17:09:58.129610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33d67323c0b8'
down_revision: Union[str, None] = '6afc59f0897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('ADMIN', 'USER', name='role'),
               existing_nullable=False)
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.alter_column('user', 'address',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='role'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'modified_at')
    # ### end Alembic commands ###
