"""update user column

Revision ID: ee2ea03ecd6f
Revises: 64b4e3882b87
Create Date: 2024-12-22 22:06:03.893257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee2ea03ecd6f'
down_revision: Union[str, None] = '64b4e3882b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('user', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified_at', mysql.DATETIME(), nullable=False))
    op.drop_column('user', 'updated_at')
    op.drop_table('login_history')
    # ### end Alembic commands ###
