"""change is_replied column type to boolean

Revision ID: f11aec663a3d
Revises: b50abbf9cdf4
Create Date: 2025-01-01 23:28:52.226933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f11aec663a3d'
down_revision: Union[str, None] = 'b50abbf9cdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquiry', 'is_replied',
               existing_type=mysql.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquiry', 'is_replied',
               existing_type=sa.Boolean(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
