"""add cascade delete to login_history

Revision ID: 6fc92e0b84e5
Revises: 30c87e24bfaf
Create Date: 2025-02-17 11:41:10.925535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc92e0b84e5'
down_revision: Union[str, None] = '30c87e24bfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('login_history_user_id_fkey', 'login_history', type_='foreignkey')
    op.create_foreign_key(None, 'login_history', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.create_foreign_key('login_history_user_id_fkey', 'login_history', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
