"""add coin column to user table

Revision ID: 3e4049c6947a
Revises: 2025_01_09_2151
Create Date: 2025-01-27 06:51:22.747507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4049c6947a'
down_revision: Union[str, None] = '2025_01_09_2151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'coin')
    # ### end Alembic commands ###
