"""add point to user and remove user_point table

Revision ID: 7d717d306f4f
Revises: ee2ea03ecd6f
Create Date: 2025-01-01 18:35:31.282703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d717d306f4f'
down_revision: Union[str, None] = 'ee2ea03ecd6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('point', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'point')
    # ### end Alembic commands ###
