"""Add foreign key relationships between User, CoinWallet, and Coin

Revision ID: caa0b8660db4
Revises: e3fed9b60c86
Create Date: 2025-02-08 04:34:35.869100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa0b8660db4'
down_revision: Union[str, None] = 'e3fed9b60c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coin', 'coin_wallet', ['wallet_id'], ['id'])
    op.create_foreign_key(None, 'coin_wallet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'login_history', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.drop_constraint(None, 'coin_wallet', type_='foreignkey')
    op.drop_constraint(None, 'coin', type_='foreignkey')
    # ### end Alembic commands ###
